# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b134648aa8f5695d69dfb40f241eac2aaf74d7cfe94d1ecd147257a212ab297ede1c316909767b78f6da250619770e421fdaebed7f4a13dbf70666293db65c35

test:
  secret_key_base: a0ddf9933d770f614007d1fecc275226e8e4aac8b8c01f2c9044d50eaf6629f8a1f5bf47ac8c51088980b1e0a20001db1374ddd9ba5c21fe4ca5acb30a3dc41a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
